### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by jfmcarreira** [fhackenberger/ktikz#8]
Hey,

Are you planning on create new releases of ktikz, either KDE4 ou 5, so we could include the features introduced in older version of Ubuntu for example. I noticed that the Ubuntu version is quiet old. I would assist you on the packaging side, as I at the moment am delivering pkg for Gentoo.

**Comment by baimafeima** [comment]
Do you have any plans to port this to Qt5?

**Comment by jfmcarreira** [comment]
As for this moment there is a port for Qt5/KDE5 in the frameworks branch

**Comment by gprud** [comment]
Thanks you @jfmcarreira for your (huge) work about porting KTikZ. 

I’m not familiar with KF5 (and I’m still using Qt4—not for a long time).
I wonder: should we keep Qt4 support for a (one or a few) next release(s)?

My concern is: should we take into account Qt4 compatibility for new features of KTikZ?

**Comment by jfmcarreira** [comment]
I think it would be interesting if we could release a new version of the software with Qt4 (e.g., the current stage of the master branch).

Besides that I do not believe it would be interesting in continuing with Qt4 development as Qt5 is already main stream in many linux distros.

**Comment by llimeht** [comment]
It is certainly the intention of the Debian Qt/KDE maintainers to [not have Qt4 and KDE4 libraries shipped in the next release](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874996). If even Debian has given up on Qt4 as being too old to support, that should probably be taken as an indication that it's not worth worrying about any more! Their timescale means there would be an upper limit of 15 months to _complete_ the migration from KDE4 to KF5; however, I would rather upload something somewhat sooner than that for testing purposes and for ktikz to not get in the way of the Qt4 removal.

@jfmcarreira the Ubuntu packages pull the Debian ones directly and so should already be more or less the current git master, since I've been tracking git master in the absence of tagged releases. (They are git master as at 2016-11-22; there have been no functional changes since then to justify uploading a newer version.)

(BTW this issue should perhaps be merged with  #4)

**Comment by llimeht** [comment]
The latest release of poppler [removes Qt4 support](https://cgit.freedesktop.org/poppler/poppler/tree/NEWS?h=poppler-0.62.0#n16) and so this issue becomes more urgent. Unless there is a viable Kf5 port completed, I will shortly need to disable building the KDE4 version in Debian (and derivatives) and build only the Qt5 version.

**Comment by jfmcarreira** [comment]
Dear Stuart,

There is a KF5 framework port in the repository. Might need a bit more
testing ans then we can merge it with master.

I have been using this port for a while without problems.

When will poopler Qt4 be removed?


--
Regards,

João Carreira

**Comment by pinotree** [comment]
> When will poopler Qt4 be removed?

It was removed in poppler 0.62.0, released at the beginning of December 2017:
https://lists.freedesktop.org/archives/poppler/2017-December/012701.html

**Comment by llimeht** [comment]
I've uploaded a snapshot of the `frameworks` branch to Debian's experimental repository. That doesn't fix the problem from Debian's perspective but it hopefully helps people test the package. For a final upload, I'd really rather upload a release or at least something from `master` rather than an unmerged branch.

**Comment by Piraty** [comment]
`qtikz 0.11`builds fine on using `Qt 5.10.1` on Void Linux.
( But as you can see, it broke my theming, like most qt5 applications do when transitioning from qt4)
![screenshot_qtikz](https://user-images.githubusercontent.com/23238955/37228530-3d202bce-23e1-11e8-9fca-15a1794621b0.png)

**Comment by jfmcarreira** [comment]
Thanks for your interest in ktikz!

A new release was just deployed so you should expect it soon on your distros. Feel free also to build it from source for a faster upgrade.

Closing this now. Please report bug in newer Qt5/KDE 5 bugs in a new issue.
